### PR TITLE
Update Author and Maintainer headers

### PR DESCRIPTION
**Pull request by basil-conto**
Re: #31.

Do you think this change makes sense @clarete? Here are the relevant header descriptions from [`(elisp) Library Headers`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html):

    ‘Author’
         This line states the name and email address of at least the
         principal author of the library.  If there are multiple authors,
         list them on continuation lines led by ‘;;’ and a tab or at least
         two spaces.  We recommend including a contact email address, of the
         form ‘<...>’.  For example:

              ;; Author: Your Name <yourname@example.com>
              ;;      Someone Else <someone@example.com>
              ;;      Another Person <another@example.com>

    ‘Maintainer’
         This header has the same format as the Author header.  It lists the
         person(s) who currently maintain(s) the file (respond to bug
         reports, etc.).

         If there is no maintainer line, the person(s) in the Author field
         is/are presumed to be the maintainers.  Some files in Emacs use
         ‘FSF’ for the maintainer.  This means that the original author is
         no longer responsible for the file, and that it is maintained as
         part of Emacs.

### CODE REVIEW

**Comment by basil-conto** [comment]
Thanks @clarete!

> I'd add your name to the copyright list within the years you've been working on the project

I'm not against this, but FYI I'm not particularly keen on being attributed or holding copyright. I'm also not particularly familiar with what is legally required.

So, would you prefer if I added my name to the copyright list even though I'm not requesting it? Would you be interested in following the advice here: https://opensource.google.com/docs/releasing/authors/ instead, by having something like `Copyright [Years] The [Project Name] Authors`?

**Comment by basil-conto** [comment]
> I really learned a ton since you started contributing with the project!

I'm glad, because I have, too. :)

**Comment by clarete** [comment]
I unsuccessfully tried to find a piece of text from the Gnu project that addresses this sort of decision. As far as I remember, copyright can be attributed to an author after they contribute with a "Relevant amount" of code. Although that's pretty subjective, I think your contributions surpassed that mark a while ago, in importance and code length. I'm pretty happy with your solution! I just really wanted to make sure that your contributions were acknowledged in the most comprehensible way!

**Comment by basil-conto** [comment]
> I feel like "Hackernews.el" would be enough for Emacs users

Same, I just hope it doesn't count as trademark infringement or similar.

**Pull request merged**
