### PR TITLE
Documented the keybindings

### PR DESCRIPTION
**Pull request by helgeblod**
* The keyboard-shortcuts were missing from the README, so I had to look
  them up in the elisp-source. Added them to the README to make them
  easier to find.

### CODE REVIEW

**Comment by clarete** [comment]
Sweeeeet!!! Thank you very much!

**Comment by helgeblod** [comment]
No prob! Very cool plugin btw, keep up the good work!

**Comment by clarete** [comment]
Thanks sir! and keep the PRs coming! :smile_cat:

**Comment by helgeblod** [comment]
Maybe I'll help out a bit when my elisp skills are a bit more up to par :)

**Comment by clarete** [comment]
\o/ Feel free to try them on hackernews.el! \o/

**Comment by helgeblod** [comment]
Cool, I might just do that 👍

**Pull request merged**
